import Head from "next/head";
import { Navbar } from "./Navbar";

export const Layouts = (props) => {
  const fontUrl =
    "https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;900&display=swap";
  return (
    <>
      <Head>
        <title>HiMTI</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
        {/* Google Font Monsterat */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href={fontUrl} />
      </Head>

      <Navbar />
      {props.children}
    </>
  );
};
